name: liquid_navbar
description: A customizable liquid-glass floating navbar with draggable indicator and parallax pages.
version: 2.0.7
homepage: https://github.com/ZyadWKhedr/Liquid_NavBar.git
repository: https://github.com/ZyadWKhedr/Liquid_NavBar.git
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  liquid_glass_renderer: ^0.2.0-dev.4
  flutter_riverpod: ^3.0.3 


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
