name: liquid_navbar
description: A customizable liquid-glass floating navbar with draggable indicator and parallax pages.
version: 0.0.1
author: Zyad Khedr <ziad.w.khedr@gmail.com>
homepage: https://github.com/ZyadWKhedr/Liquid_NavBar.git
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  liquid_glass_renderer: ^0.2.0-dev.4
  flutter_riverpod: ^3.0.3 
