name: liquid_navbar
description: A customizable liquid-glass floating navbar with draggable indicator and parallax pages.
version: 0.0.1
author: Zyad Khedr <ziad.w.khedr@gmail.com>
homepage: https://github.com/yourusername/liquid_navbar
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  liquid_glass_renderer: ^0.0.6
  flutter_riverpod: ^2.3.6 # optional if you keep Riverpod version
